# Generated by Django 4.2.7 on 2024-07-02 22:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_grupomuscular_remove_exercicio_imagem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='aluno',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='programas_inscritos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programa',
            name='exercicios',
            field=models.ManyToManyField(to='exercicios.exercicio'),
        ),
        migrations.AddField(
            model_name='programa',
            name='personal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='programas_criados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
