# Generated by Django 4.2.7 on 2024-07-04 19:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('programas', '0002_programa_aluno_programa_exercicios_programa_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_como_aluno', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programas_como_personal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='programa',
            name='tipo',
            field=models.CharField(max_length=255),
        ),
    ]
