# Generated by Django 4.2.7 on 2024-07-07 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treinos', '0001_initial'),
        ('exercicios', '0004_exercicio_imagem'),
        ('execucoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execucao',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='exercicios.exercicio'),
        ),
        migrations.AlterField(
            model_name='execucao',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='treinos.treino'),
        ),
    ]
