# Generated by Django 4.2.7 on 2024-07-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='data_avaliacao',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 1, 16, 34, 18, 171499)),
            preserve_default=False,
        ),
    ]
