# Generated by Django 5.0.6 on 2024-07-30 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='profissional',
            new_name='personal',
        ),
    ]
