# Generated by Django 4.2.7 on 2024-06-12 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_personal',
        ),
    ]
