# Generated by Django 4.2.7 on 2024-07-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0002_grupomuscular_remove_exercicio_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercicio',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.grupomuscular'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='grupomuscular',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
