# Generated by Django 4.2.7 on 2024-06-09 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0001_initial'),
        ('exercicios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.IntegerField()),
                ('repeticoes', models.IntegerField()),
                ('carga', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('completo', 'Completo')], max_length=10)),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicio')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa')),
            ],
        ),
    ]
