# Generated by Django 4.2.7 on 2024-07-02 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_programa_aluno_programa_exercicios_programa_personal'),
        ('exercicios', '0002_grupomuscular_remove_exercicio_imagem_and_more'),
        ('treinos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='treinos/'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='exercicios.exercicio'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='programas.programa'),
        ),
    ]
