# Generated by Django 4.2.7 on 2024-07-04 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercicios', '0003_alter_exercicio_grupo_alter_exercicio_nome_and_more'),
        ('programas', '0003_alter_programa_aluno_alter_programa_personal_and_more'),
        ('treinos', '0002_treino_imagem_alter_treino_exercicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treino',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='treino',
            name='carga',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='treino',
            name='exercicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercicios.exercicio'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.programa'),
        ),
        migrations.AlterField(
            model_name='treino',
            name='repeticoes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='treino',
            name='serie',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='treino',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
